server:
    port: 8442
fengtoos:
    ipaddress: 127.0.0.1
spring:
    application:
      name: blog-gateway-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
#    healthcheck:
#      enabled: true
  instance:
    ip-address: ${fengtoos.ipaddress}
    instance-id: ${spring.application.name}:${spring.cloud.client.ipaddress}:${server.port}
    prefer-ip-address: true
zuul:
  routes:
    user:
      path: /uac/**
      serviceId: blog-provider-uac
      sensitiveHeaders: "*"
    cmc:
      path: /cmc/**
      serviceId: blog-provider-cmc
      sensitiveHeaders: "*"
    template:
      path: /view/**
      serviceId: blog-template
      sensitiveHeaders: "*"
    coc:
      path: /coc/**
      serviceId: blog-provider-coc
      sensitiveHeaders: "*"
security:
  oauth2:
    client:
      access-token-uri: http://${fengtoos.ipaddress}:${server.port}/uac/oauth/token
      user-authorization-uri: http://${fengtoos.ipaddress}:${server.port}/uac/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri: http://${fengtoos.ipaddress}:${server.port}/uac/user/principal
      prefer-token-info: false
