server:
    port: 8021
fengtoos:
    address: 127.0.0.1
spring:
    application:
      name: blog-provider-cmc
    # datasource链接配置
    datasource:
      druid:
        url: jdbc:mysql://localhost:3306/blog_cloud?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
        initial-size: 5
        max-active: 20
        min-idle: 10
        max-wait: 10

    # redis 配置
    redis:
      #数据库索引
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 123
      jedis:
        pool:
          #最大连接数
          max-active: 8
          #最大阻塞等待时间(负数表示没限制)
          max-wait: -1
          #最大空闲
          max-idle: 8
          #最小空闲
          min-idle: 0
      #连接超时时间
      timeout: 10000
# mybtais配置
mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml
  type-aliases-package: com.zhuofengyuan.blog.blogprovidercmc.model

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipaddress}:${server.port}
    prefer-ip-address: true
    ip-address: ${fengtoos.address}
logging:
  config: classpath:log4j2.xml

