server:
  port: 8441

spring:
  profiles:
    active: dev
  application:
    name: blog-gateway
  cloud:
    gateway:
      routes:
      - id: blog-provider-uac
        uri: http://localhost:8001
        predicates:
        - Path=/user/**
      - id: blog-provider-cmc
        uri: lb://blog-provider-cmc
        predicates:
        - Path=/cmc/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
    prefer-ip-address: true