server:
    port: 8080
fengtoos:
    address: 127.0.0.1
spring:
  cloud:
    inetutils:
      default-ip-address:
  application:
    name: blog-template
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
    # redis 配置
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipaddress}:${server.port}
    prefer-ip-address: true
    ip-address: ${fengtoos.address}

security:
  oauth2:
    resource:
      id: blog-provider-template
      user-info-uri: http://${fengtoos.address}:8442/uac/user/principal
      prefer-token-info: false